apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wordpress-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "sandbox-vpc-eks-test-aurora-db-secret-demo"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db_username
          - path: password
            objectAlias: db_password
  secretObjects:
    - secretName: wordpress-db-secret
      type: Opaque
      data:
        - objectName: db_username
          key: db_username
        - objectName: db_password
          key: db_password
