apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      serviceAccountName: wordpress-deployment-demo-sa-updated # Ensure IAM role is associated
      containers:
      - name: wordpress
        image: wordpress:php8.1-apache  # Updated to PHP 8.1
        env:
        - name: WORDPRESS_DB_HOST
          value: sandbox-vpc-eks-test-aurora-cluster.cluster-ckx2tshx1lyr.us-west-2.rds.amazonaws.com
        - name: WORDPRESS_DB_USER
          value: ""
        - name: WORDPRESS_DB_PASSWORD
          value: ""
        command: ["/bin/sh", "-c"]
        args:
          - export WORDPRESS_DB_USER=$(cat /mnt/secrets-store/db_username);
            export WORDPRESS_DB_PASSWORD=$(cat /mnt/secrets-store/db_password);
            apache2-foreground;
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-efs-pvc
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "wordpress-aws-secrets"
